name = "BellmanPDEs"
uuid = "f5c2d71c-83f8-4255-b29d-cee59dfde9e8"
authors = ["William Pope"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
